#!/usr/bin/env bash
# vim:sw=2:ts=2

set -o errexit
set -o errtrace
set -o nounset

source ./lib/common.bash
source ./lib/bitcask.bash
source ./lib/keywords.bash

if (( ${BASH_VERSINFO[0]} != 4 ))
then
  errexit 'bash version 4 is required.'
fi

logs_dir="${1-0xdeadbeef}"
if [[ ! -d $logs_dir ]]
then
  errexit 'first argument must be a directory.'
fi

verify_commands 'grep' 'fgrep' 'egrep' 'perl'

declare -i processed=0
for log_dir in $logs_dir/*-riak-debug
do
  if [[ -d "$log_dir" ]]
  then
    node_commands_dir="$log_dir/commands"
    node_config_dir="$log_dir/config"
    node_log_dir="$log_dir/logs"
    node_ring_dir="$log_dir/ring"

    if [[ -d $node_commands_dir && -d $node_config_dir && -d $node_log_dir && -d $node_ring_dir ]]
    then
      # Extract node name from log directory, which will be in the form:
      # ./../tickets/7015/comments/7/lumi-riak@10.42.1.28-riak-debug
      tmp="${log_dir##*/}"
      nodename="${tmp%-riak-debug}"

      pinfo "NODENAME: $nodename"
      pinfo "PROCESSING: $log_dir"

      for node_log_subdir in $node_log_dir/*
      do
        for node_log_file in $node_log_subdir/*
        do
          if [[ -f $node_log_file && -s $node_log_file ]]
          then
            #
            # TODO: add all per-file handlers here.
            #
            process_bitcask "$node_log_subdir" "$node_log_file"
            process_keywords "$node_log_subdir" "$node_log_file" "$nodename"
          fi
        done
      done

      (( ++processed )) # NB: processed++ exits due to errexit
    else
      perr "required subdir missing, skipping dir $log_dir"
    fi
  fi
done

if (( processed == 0 ))
then
  perr "no subdirectories of $logs_dir matched pattern *-riak-debug. Nothing to do."
else
  #
  # TODO summaries
  #
  pinfo "processed $processed riak-debug directories."

  summary_dir='./summary'

  if [[ -d $summary_dir ]]
  then
    rm -rf "${summary_dir}_old"
    mv -f $summary_dir "${summary_dir}_old"
  fi
  mkdir $summary_dir
  consolidate_bitcask_output $summary_dir
  consolidate_keywords_output $summary_dir

  # build_summary_overview
  summary_bitcask $summary_dir
  summary_keywords $summary_dir
fi

exit 0

