#!/usr/bin/env bash
# vim:sw=2:ts=2

set -o errexit
set -o errtrace
set -o nounset

source ./lib/common.bash
# source ./lib/emfile.bash
source ./lib/riak_kv.bash

# TODO: commands used, check for existence:
# find, egrep

if (( ${BASH_VERSINFO[0]} != 4 ))
then
  errexit 'bash version 4 is required.'
fi

logs_dir="${1-0xdeadbeef}"
if [[ ! -d $logs_dir ]]
then
  errexit 'first argument must be a directory.'
fi

declare -i processed=0
for log_dir in $logs_dir/*-riak-debug
do
  if [[ -d "$log_dir" ]]
  then
    node_commands_dir="$log_dir/commands"
    node_config_dir="$log_dir/config"
    node_log_dir="$log_dir/logs"
    node_ring_dir="$log_dir/ring"

    if [[ -d $node_commands_dir && -d $node_config_dir && -d $node_log_dir && -d $node_ring_dir ]]
    then
      pinfo "PROCESSING: $log_dir"

      # TODO: call processing "plugins" here.
      hostname_file="$log_dir/commands/hostname"
      if [[ -s $hostname_file ]]
      then
        hostname="$(< $log_dir/commands/hostname)"
        pinfo "HOSTNAME: $hostname"
      fi

      for node_log_subdir in $node_log_dir/*
      do
        for node_log_file in $node_log_subdir/*
        do
          if [[ -f $node_log_file && -s $node_log_file ]]
          then
            #
            # TODO: add all per-file handlers here.
            #
            process_riak_kv "$node_log_subdir" "$node_log_file"
            # process_emfile "$node_log_subdir" "$node_log_file"
          fi
        done
      done

      (( ++processed )) # NB: processed++ exits due to errexit
    else
      perr "required subdir missing, skipping dir $log_dir"
    fi
  fi
done

if (( processed == 0 ))
then
  perr "no subdirectories of $logs_dir matched pattern *-riak-debug. Nothing to do."
else
  #
  # TODO summaries
  #
  pinfo "processed $processed riak-debug directories."

  summary_dir='./summary'

  if [[ -d $summary_dir ]]
  then
    mv -f $summary_dir "${summary_dir}_old"
  fi
  mkdir $summary_dir
  consolidate_riak_kv_output $summary_dir
  # consolidate_emfile_output $summary_dir

  # build_summary_overview
  # summary_emfile
  summary_riak_kv
fi

# while read -r host_file
# do
#   echo "HOSTFILE: $(< $host_file)"
# done < <(find "$logs_dir" \( -type d -name .info -prune \) -o \( -type f -name 'hostname' -print \) )
# 
# while read -r log_path
# do
#   if [[ $log_path == *@* ]]
#   then
#     echo "LOG PATH: $log_path"
#   fi
# done < <(find "$logs_dir" -type f -name '*.log*')
